---
openapi: '3.0.0'
info:
  description: Backend API for Dyondo muliti-user blogging platform
  version: 1.0.0
  title: Dyondo API
paths:
    $ref: "paths/index.yaml"
components:
    schemas:
        $ref: "definitions/index.yaml"
    securitySchemes:
      BearerAuth:
        type: http
        description: JWT Authorization header using the Bearer scheme
        scheme: bearer
        bearerFormat: JWT