version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:17.3.1
    steps:
      - checkout
      - run: 
          node --version
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/**/*.js -r dotenv/config
workflows:
  build_test:
    jobs:
      - run_tests