version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    steps:
      - checkout 
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/**/*.js -r dotenv/config
workflows:
  build_test:
    jobs:
      - run_tests